# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_textBox = QtWidgets.QLineEdit(self.centralwidget)
        self.input_textBox.setEnabled(True)
        self.input_textBox.setGeometry(QtCore.QRect(320, 60, 133, 20))
        self.input_textBox.setAutoFillBackground(True)
        self.input_textBox.setFrame(False)
        self.input_textBox.setAlignment(QtCore.Qt.AlignCenter)
        self.input_textBox.setReadOnly(True)
        self.input_textBox.setObjectName("input_textBox")
        self.input_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_lineEdit.setEnabled(True)
        self.input_lineEdit.setGeometry(QtCore.QRect(20, 100, 731, 61))
        self.input_lineEdit.setFrame(False)
        self.input_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.input_lineEdit.setReadOnly(True)
        self.input_lineEdit.setObjectName("input_lineEdit")
        self.output_textBox = QtWidgets.QLineEdit(self.centralwidget)
        self.output_textBox.setGeometry(QtCore.QRect(320, 210, 133, 20))
        self.output_textBox.setAutoFillBackground(True)
        self.output_textBox.setFrame(False)
        self.output_textBox.setAlignment(QtCore.Qt.AlignCenter)
        self.output_textBox.setReadOnly(True)
        self.output_textBox.setObjectName("output_textBox")
        self.output_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.output_lineEdit.setEnabled(True)
        self.output_lineEdit.setGeometry(QtCore.QRect(20, 250, 728, 61))
        self.output_lineEdit.setText("")
        self.output_lineEdit.setFrame(False)
        self.output_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lineEdit.setReadOnly(True)
        self.output_lineEdit.setObjectName("output_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName("menubar")
        self.menuVoice_Assistant = QtWidgets.QMenu(self.menubar)
        self.menuVoice_Assistant.setObjectName("menuVoice_Assistant")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuVoice_Assistant.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.input_textBox.setText(_translate("MainWindow", "Your input"))
        self.output_textBox.setText(_translate("MainWindow", "My output"))
        self.menuVoice_Assistant.setTitle(_translate("MainWindow", "Voice Assistant"))
